server:
  port: 8080
spring:
    application:
      name:tutorialsService
#main:
#      allow-bean-definition-overriding: true
data:
mongodb:
host: mongo_DB # Usa el nombre del contenedor en Docker en lugar de la IP
port: 27017
database: tutorialsservice_db # Asegúrate de usar el nombre correcto de la base de datos
